import { Websfz } from "../websfz";

export const C80: Websfz = {
  meta: {
    name: "CP80",
    formats: ["ogg", "m4a"],
    baseUrl: "https://danigb.github.io/samples/gs-e-pianos/CP80/",
    websfzUrl:
      "https://danigb.github.io/samples/gs-e-pianos/CP80/cp80.websfz.json",
    source: "https://github.com/sfzinstruments/GregSullivan.E-Pianos",
    license: "Creative Commons Attribution 3.0 Unported License",
  },
  global: {
    default_path: "Samples/",
    label_cc7: "Vol",
    label_cc10: "Pan",
    label_cc72: "Release",
    label_cc99: "Veltrack",
    set_cc7: 100,
    set_hdcc10: 0,
    set_hdcc72: 0,
    set_hdcc99: 1,
    amplitude_oncc7: 100,
    amplitude_curvecc7: 4,
    pan_oncc10: 100,
    pan_curvecc10: 1,
    ampeg_attack: 0,
    ampeg_hold: 10,
    ampeg_holdcc133: -9,
    ampeg_decay: 40,
    ampeg_decaycc133: -35,
    ampeg_sustain: 0,
    ampeg_release_oncc72: 2,
    amp_veltrack: 0,
    amp_veltrack_oncc99: 100,
    note_polyphony: 1,
    off_time: 0,
  },
  groups: [
    {
      regions: [
        {
          region_label: 1,
          lokey: 21,
          hikey: 30,
          pitch_keycenter: 27,
          volume: -2,
          sample: "027-D#1-PP",
        },
        {
          region_label: 2,
          lokey: 31,
          hikey: 37,
          pitch_keycenter: 34,
          volume: -3,
          sample: "034-A#1-PP",
        },
        {
          region_label: 3,
          lokey: 38,
          hikey: 45,
          pitch_keycenter: 42,
          volume: -4,
          sample: "042-F#2-PP",
        },
        {
          region_label: 4,
          lokey: 46,
          hikey: 53,
          pitch_keycenter: 50,
          volume: -6,
          sample: "050-D3-PP",
        },
        {
          region_label: 5,
          lokey: 54,
          hikey: 59,
          pitch_keycenter: 57,
          volume: -6,
          sample: "057-A3-PP",
        },
        {
          region_label: 6,
          lokey: 60,
          hikey: 63,
          pitch_keycenter: 63,
          volume: -6,
          sample: "063-D#4-PP",
        },
        {
          region_label: 7,
          lokey: 64,
          hikey: 66,
          pitch_keycenter: 65,
          volume: -6,
          sample: "065-F4-PP",
        },
        {
          region_label: 8,
          lokey: 67,
          hikey: 69,
          pitch_keycenter: 68,
          volume: -6,
          sample: "068-G#4-PP",
        },
        {
          region_label: 9,
          lokey: 70,
          hikey: 75,
          pitch_keycenter: 72,
          volume: -6,
          sample: "072-C5-PP",
        },
        {
          region_label: 10,
          lokey: 76,
          hikey: 82,
          pitch_keycenter: 80,
          volume: -6,
          sample: "080-G#5-PP",
        },
        {
          region_label: 11,
          lokey: 83,
          hikey: 87,
          pitch_keycenter: 85,
          volume: -6,
          sample: "085-C#6-PP",
        },
        {
          region_label: 12,
          lokey: 88,
          hikey: 93,
          pitch_keycenter: 91,
          volume: -6,
          sample: "091-G6-PP",
        },
        {
          region_label: 13,
          lokey: 94,
          hikey: 99,
          pitch_keycenter: 97,
          volume: -6,
          sample: "097-C#7-PP",
        },
        {
          region_label: 14,
          lokey: 100,
          hikey: 104,
          pitch_keycenter: 102,
          volume: -6,
          sample: "102-F#7-PP",
          end: 109256,
        },
      ],
      lovel: 1,
      hivel: 49,
      group_label: "PP",
    },
    {
      regions: [
        {
          region_label: 15,
          lokey: 105,
          hikey: 108,
          pitch_keycenter: 107,
          volume: -6,
          sample: "107-B7-PP",
          end: 102347,
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 30,
          pitch_keycenter: 27,
          volume: -2,
          sample: "027-D#1-MP",
        },
        {
          region_label: 2,
          lokey: 31,
          hikey: 37,
          pitch_keycenter: 34,
          volume: -3,
          sample: "034-A#1-MP",
        },
        {
          region_label: 3,
          lokey: 38,
          hikey: 43,
          pitch_keycenter: 42,
          volume: -3,
          sample: "042-F#2-MP",
        },
        {
          region_label: 4,
          lokey: 44,
          hikey: 47,
          pitch_keycenter: 46,
          volume: -4,
          sample: "046-A#2-MP",
        },
        {
          region_label: 5,
          lokey: 48,
          hikey: 51,
          pitch_keycenter: 50,
          volume: -6,
          sample: "050-D3-MP",
        },
        {
          region_label: 6,
          lokey: 52,
          hikey: 54,
          pitch_keycenter: 53,
          volume: -4,
          sample: "053-F3-MP",
        },
        {
          region_label: 7,
          lokey: 55,
          hikey: 58,
          pitch_keycenter: 57,
          volume: -6,
          sample: "057-A3-MP",
        },
        {
          region_label: 8,
          lokey: 59,
          hikey: 61,
          pitch_keycenter: 60,
          volume: -6,
          sample: "060-C4-MP",
        },
        {
          region_label: 9,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 63,
          volume: -6,
          sample: "063-D#4-MP",
        },
        {
          region_label: 10,
          lokey: 64,
          hikey: 66,
          pitch_keycenter: 65,
          volume: -6,
          sample: "065-F4-MP",
        },
        {
          region_label: 11,
          lokey: 67,
          hikey: 69,
          pitch_keycenter: 68,
          volume: -6,
          sample: "068-G#4-MP",
        },
        {
          region_label: 12,
          lokey: 70,
          hikey: 73,
          pitch_keycenter: 72,
          volume: -6,
          sample: "072-C5-MP",
        },
        {
          region_label: 13,
          lokey: 74,
          hikey: 77,
          pitch_keycenter: 76,
          volume: -4,
          sample: "076-E5-MP",
        },
        {
          region_label: 14,
          lokey: 78,
          hikey: 80,
          pitch_keycenter: 80,
          volume: -3,
          sample: "080-G#5-MP",
        },
        {
          region_label: 15,
          lokey: 81,
          hikey: 83,
          pitch_keycenter: 82,
          volume: -3,
          sample: "082-A#5-MP",
        },
        {
          region_label: 16,
          lokey: 84,
          hikey: 86,
          pitch_keycenter: 85,
          volume: -4,
          sample: "085-C#6-MP",
        },
        {
          region_label: 17,
          lokey: 87,
          hikey: 89,
          pitch_keycenter: 88,
          volume: -4,
          sample: "088-E6-MP",
        },
        {
          region_label: 18,
          lokey: 90,
          hikey: 92,
          pitch_keycenter: 91,
          volume: -5,
          sample: "091-G6-MP",
        },
        {
          region_label: 19,
          lokey: 93,
          hikey: 95,
          pitch_keycenter: 95,
          volume: -5,
          sample: "095-B6-MP",
        },
        {
          region_label: 20,
          lokey: 96,
          hikey: 99,
          pitch_keycenter: 97,
          volume: -5,
          sample: "097-C#7-MP",
        },
        {
          region_label: 21,
          lokey: 100,
          hikey: 104,
          pitch_keycenter: 102,
          volume: -7,
          sample: "102-F#7-MP",
        },
      ],
      lovel: 50,
      hivel: 81,
      group_label: "MP",
    },
    {
      regions: [
        {
          region_label: 22,
          lokey: 105,
          hikey: 108,
          pitch_keycenter: 107,
          volume: -5,
          sample: "107-B7-MP",
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 30,
          pitch_keycenter: 27,
          volume: -2,
          sample: "027-D#1-F",
        },
        {
          region_label: 2,
          lokey: 31,
          hikey: 38,
          pitch_keycenter: 35,
          volume: -3,
          sample: "035-B1-F",
        },
        {
          region_label: 3,
          lokey: 39,
          hikey: 43,
          pitch_keycenter: 42,
          volume: -3,
          sample: "042-F#2-F",
        },
        {
          region_label: 4,
          lokey: 44,
          hikey: 47,
          pitch_keycenter: 46,
          volume: -4,
          sample: "046-A#2-F",
        },
        {
          region_label: 5,
          lokey: 48,
          hikey: 51,
          pitch_keycenter: 50,
          volume: -6,
          sample: "050-D3-F",
        },
        {
          region_label: 6,
          lokey: 52,
          hikey: 54,
          pitch_keycenter: 53,
          volume: -4,
          sample: "053-F3-F",
        },
        {
          region_label: 7,
          lokey: 55,
          hikey: 58,
          pitch_keycenter: 57,
          volume: -6,
          sample: "057-A3-F",
        },
        {
          region_label: 8,
          lokey: 59,
          hikey: 61,
          pitch_keycenter: 60,
          volume: -6,
          sample: "060-C4-F",
        },
        {
          region_label: 9,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 63,
          volume: -6,
          sample: "063-D#4-F",
        },
        {
          region_label: 10,
          lokey: 64,
          hikey: 66,
          pitch_keycenter: 65,
          volume: -6,
          sample: "065-F4-F",
        },
        {
          region_label: 11,
          lokey: 67,
          hikey: 69,
          pitch_keycenter: 68,
          volume: -6,
          sample: "068-G#4-F",
        },
        {
          region_label: 12,
          lokey: 70,
          hikey: 73,
          pitch_keycenter: 72,
          volume: -6,
          sample: "072-C5-F",
        },
        {
          region_label: 13,
          lokey: 74,
          hikey: 77,
          pitch_keycenter: 76,
          volume: -4,
          sample: "076-E5-F",
        },
        {
          region_label: 14,
          lokey: 78,
          hikey: 80,
          pitch_keycenter: 80,
          volume: -3,
          sample: "080-G#5-F",
        },
        {
          region_label: 15,
          lokey: 81,
          hikey: 83,
          pitch_keycenter: 82,
          volume: -3,
          sample: "082-A#5-F",
        },
        {
          region_label: 16,
          lokey: 84,
          hikey: 86,
          pitch_keycenter: 85,
          volume: -4,
          sample: "085-C#6-F",
        },
        {
          region_label: 17,
          lokey: 87,
          hikey: 89,
          pitch_keycenter: 88,
          volume: -4,
          sample: "088-E6-F",
        },
        {
          region_label: 18,
          lokey: 90,
          hikey: 92,
          pitch_keycenter: 91,
          volume: -5,
          sample: "091-G6-F",
        },
        {
          region_label: 19,
          lokey: 93,
          hikey: 95,
          pitch_keycenter: 95,
          volume: -5,
          sample: "095-B6-F",
        },
        {
          region_label: 20,
          lokey: 96,
          hikey: 99,
          pitch_keycenter: 97,
          volume: -5,
          sample: "097-C#7-F",
        },
        {
          region_label: 21,
          lokey: 100,
          hikey: 104,
          pitch_keycenter: 102,
          volume: -7,
          sample: "102-F#7-F",
        },
      ],
      lovel: 82,
      hivel: 103,
      group_label: "F",
    },
    {
      regions: [
        {
          region_label: 22,
          lokey: 105,
          hikey: 108,
          pitch_keycenter: 107,
          volume: -5,
          sample: "107-B7-F",
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 30,
          pitch_keycenter: 27,
          volume: -2,
          sample: "027-D#1-FF",
        },
        {
          region_label: 2,
          lokey: 31,
          hikey: 38,
          pitch_keycenter: 35,
          volume: -3,
          sample: "035-B1-FF",
        },
        {
          region_label: 3,
          lokey: 39,
          hikey: 43,
          pitch_keycenter: 42,
          volume: -3,
          sample: "042-F#2-FF",
        },
        {
          region_label: 4,
          lokey: 44,
          hikey: 47,
          pitch_keycenter: 46,
          volume: -4,
          sample: "046-A#2-FF",
        },
        {
          region_label: 5,
          lokey: 48,
          hikey: 51,
          pitch_keycenter: 50,
          volume: -6,
          sample: "050-D3-FF",
        },
        {
          region_label: 6,
          lokey: 52,
          hikey: 54,
          pitch_keycenter: 53,
          volume: -4,
          sample: "053-F3-FF",
        },
        {
          region_label: 7,
          lokey: 55,
          hikey: 58,
          pitch_keycenter: 57,
          volume: -6,
          sample: "057-A3-FF",
        },
        {
          region_label: 8,
          lokey: 59,
          hikey: 61,
          pitch_keycenter: 60,
          volume: -6,
          sample: "060-C4-FF",
        },
        {
          region_label: 9,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 63,
          volume: -6,
          sample: "063-D#4-FF",
        },
        {
          region_label: 10,
          lokey: 64,
          hikey: 66,
          pitch_keycenter: 65,
          volume: -6,
          sample: "065-F4-FF",
        },
        {
          region_label: 11,
          lokey: 67,
          hikey: 69,
          pitch_keycenter: 68,
          volume: -6,
          sample: "068-G#4-FF",
        },
        {
          region_label: 12,
          lokey: 70,
          hikey: 73,
          pitch_keycenter: 72,
          volume: -6,
          sample: "072-C5-FF",
        },
        {
          region_label: 13,
          lokey: 74,
          hikey: 77,
          pitch_keycenter: 76,
          volume: -4,
          sample: "076-E5-FF",
        },
        {
          region_label: 14,
          lokey: 78,
          hikey: 80,
          pitch_keycenter: 80,
          volume: -3,
          sample: "080-G#5-FF",
        },
        {
          region_label: 15,
          lokey: 81,
          hikey: 83,
          pitch_keycenter: 82,
          volume: -3,
          sample: "082-A#5-FF",
        },
        {
          region_label: 16,
          lokey: 84,
          hikey: 86,
          pitch_keycenter: 85,
          volume: -4,
          sample: "085-C#6-FF",
        },
        {
          region_label: 17,
          lokey: 87,
          hikey: 89,
          pitch_keycenter: 88,
          volume: -4,
          sample: "088-E6-FF",
        },
        {
          region_label: 18,
          lokey: 90,
          hikey: 92,
          pitch_keycenter: 91,
          volume: -5,
          sample: "091-G6-FF",
        },
        {
          region_label: 19,
          lokey: 93,
          hikey: 95,
          pitch_keycenter: 95,
          volume: -5,
          sample: "095-B6-FF",
        },
        {
          region_label: 20,
          lokey: 96,
          hikey: 99,
          pitch_keycenter: 97,
          volume: -5,
          sample: "097-C#7-FF",
        },
        {
          region_label: 21,
          lokey: 100,
          hikey: 104,
          pitch_keycenter: 102,
          volume: -7,
          sample: "102-F#7-FF",
        },
      ],
      lovel: 104,
      hivel: 127,
      group_label: "FF",
    },
  ],
};
