export const GRANDPIANO = {
  meta: {
    name: "Splendid Grand Piano",
    description: "Steinway samples with 4 velocity groups",
    source: "https://github.com/sfzinstruments/SplendidGrandPiano",
    license: "Public Domain",
  },
  global: {
    default_path: "Samples/",
    label_cc7: "Vol",
    label_cc10: "Pan",
    label_cc64: "Sus.Pedal",
    label_cc70: "Resonance",
    label_cc72: "Release",
    label_cc99: "Veltrack",
    set_cc7: 100,
    set_hdcc10: 0,
    set_hdcc70: 0,
    set_hdcc72: 0,
    set_hdcc99: 1,
    amplitude_oncc7: 100,
    amplitude_curvecc7: 4,
    pan_oncc10: 100,
    pan_curvecc10: 1,
    ampeg_attack: 0,
    ampeg_hold: 8,
    ampeg_hold_oncc133: -6,
    ampeg_decay: 80,
    ampeg_decay_oncc133: -60,
    ampeg_sustain: 0,
    ampeg_release_oncc72: 2,
    amp_veltrack_oncc99: -100,
    amp_veltrack_curvecc99: 2,
    note_polyphony: 1,
    off_time: 0,
  },
  groups: [
    {
      regions: [
        { lokey: 21, hikey: 22, pitch_keycenter: 33, sample: "PP-A0" },
        {
          lokey: 23,
          hikey: 23,
          pitch_keycenter: 35,
          sample: "PP-B0",
          offset: 618,
        },
        { lokey: 24, hikey: 25, pitch_keycenter: 37, sample: "PP-C#1" },
        {
          lokey: 26,
          hikey: 27,
          pitch_keycenter: 38,
          sample: "PP-D1",
          offset: 1046,
        },
        { lokey: 28, hikey: 28, pitch_keycenter: 40, sample: "PP-E1" },
        { lokey: 29, hikey: 29, pitch_keycenter: 41, sample: "PP-F1" },
        { lokey: 30, hikey: 32, pitch_keycenter: 43, sample: "PP-G1" },
        { lokey: 33, hikey: 34, pitch_keycenter: 45, sample: "PP-A1" },
        { lokey: 35, hikey: 35, pitch_keycenter: 47, sample: "PP-B1" },
        { lokey: 36, hikey: 37, pitch_keycenter: 48, sample: "PP-C2" },
        { lokey: 38, hikey: 38, pitch_keycenter: 50, sample: "PP-D2" },
        { lokey: 39, hikey: 40, pitch_keycenter: 52, sample: "PP-E2" },
        { lokey: 41, hikey: 42, pitch_keycenter: 53, sample: "PP-F2" },
        { lokey: 43, hikey: 43, pitch_keycenter: 55, sample: "PP-G2" },
        { lokey: 44, hikey: 44, pitch_keycenter: 56, sample: "PP-G#2" },
        { lokey: 45, hikey: 45, pitch_keycenter: 57, sample: "PP-A2" },
        { lokey: 46, hikey: 46, pitch_keycenter: 58, sample: "PP-A#2" },
        { lokey: 47, hikey: 47, pitch_keycenter: 59, sample: "PP-B2" },
        { lokey: 48, hikey: 49, pitch_keycenter: 60, sample: "PP-C3" },
        { lokey: 50, hikey: 51, pitch_keycenter: 62, sample: "PP-D3" },
        { lokey: 52, hikey: 52, pitch_keycenter: 64, sample: "PP-E3" },
        { lokey: 53, hikey: 54, pitch_keycenter: 65, sample: "PP-F3" },
        { lokey: 55, hikey: 56, pitch_keycenter: 67, sample: "PP-G3" },
        { lokey: 57, hikey: 57, pitch_keycenter: 69, sample: "PP-A3" },
        { lokey: 58, hikey: 59, pitch_keycenter: 71, sample: "PP-B3" },
        { lokey: 60, hikey: 61, pitch_keycenter: 72, sample: "PP-C4" },
        { lokey: 62, hikey: 63, pitch_keycenter: 74, sample: "PP-D4" },
        { lokey: 64, hikey: 64, pitch_keycenter: 76, sample: "PP-E4" },
        { lokey: 65, hikey: 66, pitch_keycenter: 77, sample: "PP-F4" },
        { lokey: 67, hikey: 67, pitch_keycenter: 79, sample: "PP-G4" },
        { lokey: 68, hikey: 68, pitch_keycenter: 80, sample: "PP-G#4" },
        { lokey: 69, hikey: 69, pitch_keycenter: 81, sample: "PP-A4" },
        { lokey: 70, hikey: 70, pitch_keycenter: 82, sample: "PP-A#4" },
        { lokey: 71, hikey: 71, pitch_keycenter: 83, sample: "PP-B4" },
        { lokey: 72, hikey: 73, pitch_keycenter: 85, sample: "PP-C#5" },
        { lokey: 74, hikey: 74, pitch_keycenter: 86, sample: "PP-D5" },
        { lokey: 75, hikey: 75, pitch_keycenter: 87, sample: "PP-D#5" },
        { lokey: 76, hikey: 77, pitch_keycenter: 89, sample: "PP-F5" },
        {
          lokey: 78,
          hikey: 78,
          pitch_keycenter: 90,
          sample: "PP-F#5",
          pan: -40,
        },
        {
          lokey: 79,
          hikey: 79,
          pitch_keycenter: 91,
          sample: "PP-G5",
          pan: -30,
          offset: 135,
        },
        {
          lokey: 80,
          hikey: 80,
          pitch_keycenter: 92,
          sample: "PP-G#5",
          pan: -30,
        },
        {
          lokey: 81,
          hikey: 81,
          pitch_keycenter: 93,
          sample: "PP-A5",
          pan: -45,
        },
        {
          lokey: 82,
          hikey: 82,
          pitch_keycenter: 94,
          sample: "PP-A#5",
          pan: -45,
        },
        {
          lokey: 83,
          hikey: 83,
          pitch_keycenter: 95,
          sample: "PP-B5",
          offset: 324,
        },
        {
          lokey: 84,
          hikey: 84,
          pitch_keycenter: 96,
          sample: "PP-C6",
          offset: 57,
          tune: -5,
        },
        {
          lokey: 85,
          hikey: 85,
          pitch_keycenter: 97,
          sample: "PP-C#6",
          offset: 265,
          tune: -5,
        },
        {
          lokey: 86,
          hikey: 86,
          pitch_keycenter: 98,
          sample: "PP-D6",
          tune: -10,
        },
        {
          lokey: 87,
          hikey: 87,
          pitch_keycenter: 99,
          sample: "PP-D#6",
          tune: -5,
        },
        {
          lokey: 88,
          hikey: 88,
          pitch_keycenter: 100,
          sample: "PP-E6",
          tune: -10,
        },
        {
          lokey: 89,
          hikey: 89,
          pitch_keycenter: 101,
          sample: "PP-F6",
          tune: -10,
        },
        {
          lokey: 90,
          hikey: 90,
          pitch_keycenter: 102,
          sample: "PP-F#6",
          tune: -20,
        },
        {
          lokey: 91,
          hikey: 91,
          pitch_keycenter: 103,
          sample: "PP-G6",
          tune: -20,
        },
        {
          lokey: 92,
          hikey: 92,
          pitch_keycenter: 104,
          sample: "PP-G#6",
          tune: -25,
        },
        {
          lokey: 93,
          hikey: 93,
          pitch_keycenter: 105,
          sample: "PP-A6",
          offset: 146,
          tune: -20,
        },
        {
          lokey: 94,
          hikey: 94,
          pitch_keycenter: 106,
          sample: "PP-A#6",
          tune: -25,
        },
        {
          lokey: 95,
          hikey: 95,
          pitch_keycenter: 107,
          sample: "PP-B6",
          tune: -25,
        },
      ],
      group: 1,
      locc64: 65,
      locc70: 1,
      amplitude_oncc70: 200,
      group_volume: -11,
      ampeg_attack: 0,
    },
    {
      regions: [
        {
          lokey: 96,
          hikey: 96,
          pitch_keycenter: 108,
          sample: "PP-C7",
          tune: -20,
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 24,
          pitch_keycenter: 23,
          ampeg_release: 0,
          sample: "PP-B-1",
        },
        {
          region_label: 2,
          lokey: 25,
          hikey: 27,
          pitch_keycenter: 27,
          ampeg_release: 0,
          sample: "PP-D#0",
        },
        {
          region_label: 3,
          lokey: 28,
          hikey: 30,
          pitch_keycenter: 29,
          ampeg_release: 0,
          sample: "PP-F0",
        },
        {
          region_label: 4,
          lokey: 31,
          hikey: 32,
          pitch_keycenter: 31,
          ampeg_release: 0,
          sample: "PP-G0",
        },
        {
          region_label: 5,
          lokey: 33,
          hikey: 34,
          pitch_keycenter: 33,
          ampeg_release: 0,
          sample: "PP-A0",
        },
        {
          region_label: 6,
          lokey: 35,
          hikey: 35,
          pitch_keycenter: 35,
          ampeg_release: 0,
          sample: "PP-B0",
          offset: 618,
        },
        {
          region_label: 7,
          lokey: 36,
          hikey: 37,
          pitch_keycenter: 37,
          sample: "PP-C#1",
          volume: 1,
        },
        {
          region_label: 8,
          lokey: 38,
          hikey: 39,
          pitch_keycenter: 38,
          sample: "PP-D1",
          offset: 1046,
        },
        {
          region_label: 9,
          lokey: 40,
          hikey: 40,
          pitch_keycenter: 40,
          sample: "PP-E1",
        },
        {
          region_label: 10,
          lokey: 41,
          hikey: 41,
          pitch_keycenter: 41,
          sample: "PP-F1",
        },
        {
          region_label: 11,
          lokey: 42,
          hikey: 44,
          pitch_keycenter: 43,
          sample: "PP-G1",
        },
        {
          region_label: 12,
          lokey: 45,
          hikey: 46,
          pitch_keycenter: 45,
          sample: "PP-A1",
        },
        {
          region_label: 13,
          lokey: 47,
          hikey: 47,
          pitch_keycenter: 47,
          sample: "PP-B1",
        },
        {
          region_label: 14,
          lokey: 48,
          hikey: 49,
          pitch_keycenter: 48,
          sample: "PP-C2",
        },
        {
          region_label: 15,
          lokey: 50,
          hikey: 50,
          pitch_keycenter: 50,
          sample: "PP-D2",
        },
        {
          region_label: 16,
          lokey: 51,
          hikey: 52,
          pitch_keycenter: 52,
          sample: "PP-E2",
        },
        {
          region_label: 17,
          lokey: 53,
          hikey: 54,
          pitch_keycenter: 53,
          sample: "PP-F2",
        },
        {
          region_label: 18,
          lokey: 55,
          hikey: 55,
          pitch_keycenter: 55,
          sample: "PP-G2",
        },
        {
          region_label: 19,
          lokey: 56,
          hikey: 56,
          pitch_keycenter: 56,
          sample: "PP-G#2",
        },
        {
          region_label: 20,
          lokey: 57,
          hikey: 57,
          pitch_keycenter: 57,
          sample: "PP-A2",
        },
        {
          region_label: 21,
          lokey: 58,
          hikey: 58,
          pitch_keycenter: 58,
          sample: "PP-A#2",
        },
        {
          region_label: 22,
          lokey: 59,
          hikey: 59,
          pitch_keycenter: 59,
          sample: "PP-B2",
        },
        {
          region_label: 23,
          lokey: 60,
          hikey: 61,
          pitch_keycenter: 60,
          sample: "PP-C3",
        },
        {
          region_label: 24,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 62,
          sample: "PP-D3",
        },
        {
          region_label: 25,
          lokey: 64,
          hikey: 64,
          pitch_keycenter: 64,
          sample: "PP-E3",
        },
        {
          region_label: 26,
          lokey: 65,
          hikey: 66,
          pitch_keycenter: 65,
          sample: "PP-F3",
        },
        {
          region_label: 27,
          lokey: 67,
          hikey: 68,
          pitch_keycenter: 67,
          sample: "PP-G3",
        },
        {
          region_label: 28,
          lokey: 69,
          hikey: 69,
          pitch_keycenter: 69,
          sample: "PP-A3",
        },
        {
          region_label: 29,
          lokey: 70,
          hikey: 71,
          pitch_keycenter: 71,
          sample: "PP-B3",
        },
        {
          region_label: 30,
          lokey: 72,
          hikey: 73,
          pitch_keycenter: 72,
          sample: "PP-C4",
        },
        {
          region_label: 31,
          lokey: 74,
          hikey: 75,
          pitch_keycenter: 74,
          sample: "PP-D4",
        },
        {
          region_label: 32,
          lokey: 76,
          hikey: 76,
          pitch_keycenter: 76,
          sample: "PP-E4",
        },
        {
          region_label: 33,
          lokey: 77,
          hikey: 78,
          pitch_keycenter: 77,
          sample: "PP-F4",
        },
        {
          region_label: 34,
          lokey: 79,
          hikey: 79,
          pitch_keycenter: 79,
          sample: "PP-G4",
        },
        {
          region_label: 35,
          lokey: 80,
          hikey: 80,
          pitch_keycenter: 80,
          sample: "PP-G#4",
        },
        {
          region_label: 36,
          lokey: 81,
          hikey: 81,
          pitch_keycenter: 81,
          sample: "PP-A4",
        },
        {
          region_label: 37,
          lokey: 82,
          hikey: 82,
          pitch_keycenter: 82,
          sample: "PP-A#4",
        },
        {
          region_label: 38,
          lokey: 83,
          hikey: 83,
          pitch_keycenter: 83,
          sample: "PP-B4",
        },
        {
          region_label: 39,
          lokey: 84,
          hikey: 85,
          pitch_keycenter: 85,
          ampeg_release: 0,
          sample: "PP-C#5",
        },
        {
          region_label: 40,
          lokey: 86,
          hikey: 86,
          pitch_keycenter: 86,
          ampeg_release: 0,
          sample: "PP-D5",
        },
        {
          region_label: 41,
          lokey: 87,
          hikey: 87,
          pitch_keycenter: 87,
          ampeg_release: 0,
          sample: "PP-D#5",
        },
        {
          region_label: 42,
          lokey: 88,
          hikey: 89,
          pitch_keycenter: 89,
          ampeg_release: 0,
          sample: "PP-F5",
        },
        {
          region_label: 43,
          lokey: 90,
          hikey: 90,
          pitch_keycenter: 90,
          ampeg_release: 0,
          sample: "PP-F#5",
          pan: -40,
        },
        {
          region_label: 44,
          lokey: 91,
          hikey: 91,
          pitch_keycenter: 91,
          ampeg_release: 10,
          sample: "PP-G5",
          pan: -30,
          offset: 135,
        },
        {
          region_label: 45,
          lokey: 92,
          hikey: 92,
          pitch_keycenter: 92,
          ampeg_release: 10,
          sample: "PP-G#5",
          pan: -30,
        },
        {
          region_label: 46,
          lokey: 93,
          hikey: 93,
          pitch_keycenter: 93,
          ampeg_release: 10,
          sample: "PP-A5",
          pan: -45,
        },
        {
          region_label: 47,
          lokey: 94,
          hikey: 94,
          pitch_keycenter: 94,
          ampeg_release: 10,
          sample: "PP-A#5",
          pan: -45,
        },
        {
          region_label: 48,
          lokey: 95,
          hikey: 95,
          pitch_keycenter: 95,
          ampeg_release: 10,
          sample: "PP-B5",
          offset: 324,
        },
        {
          region_label: 49,
          lokey: 96,
          hikey: 96,
          pitch_keycenter: 96,
          ampeg_release: 10,
          sample: "PP-C6",
          offset: 57,
        },
        {
          region_label: 50,
          lokey: 97,
          hikey: 97,
          pitch_keycenter: 97,
          ampeg_release: 10,
          sample: "PP-C#6",
          offset: 265,
        },
        {
          region_label: 51,
          lokey: 98,
          hikey: 98,
          pitch_keycenter: 98,
          ampeg_release: 10,
          sample: "PP-D6",
        },
        {
          region_label: 52,
          lokey: 99,
          hikey: 99,
          pitch_keycenter: 99,
          ampeg_release: 10,
          sample: "PP-D#6",
        },
        {
          region_label: 53,
          lokey: 100,
          hikey: 100,
          pitch_keycenter: 100,
          ampeg_release: 10,
          sample: "PP-E6",
        },
        {
          region_label: 54,
          lokey: 101,
          hikey: 101,
          pitch_keycenter: 101,
          ampeg_release: 10,
          sample: "PP-F6",
        },
        {
          region_label: 55,
          lokey: 102,
          hikey: 102,
          pitch_keycenter: 102,
          ampeg_release: 10,
          sample: "PP-F#6",
        },
        {
          region_label: 56,
          lokey: 103,
          hikey: 103,
          pitch_keycenter: 103,
          ampeg_release: 10,
          sample: "PP-G6",
        },
        {
          region_label: 57,
          lokey: 104,
          hikey: 104,
          pitch_keycenter: 104,
          ampeg_release: 10,
          sample: "PP-G#6",
        },
        {
          region_label: 58,
          lokey: 105,
          hikey: 105,
          pitch_keycenter: 105,
          ampeg_release: 10,
          sample: "PP-A6",
          offset: 146,
        },
        {
          region_label: 59,
          lokey: 106,
          hikey: 106,
          pitch_keycenter: 106,
          ampeg_release: 10,
          sample: "PP-A#6",
        },
        {
          region_label: 60,
          lokey: 107,
          hikey: 107,
          pitch_keycenter: 107,
          ampeg_release: 10,
          sample: "PP-B6",
        },
      ],
      lovel: 1,
      hivel: 40,
      cutoff: 1000,
      group_volume: 0,
      group_label: "PPP",
    },
    {
      regions: [
        {
          region_label: 61,
          lokey: 108,
          hikey: 108,
          pitch_keycenter: 108,
          ampeg_release: 10,
          sample: "PP-C7",
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 24,
          pitch_keycenter: 23,
          ampeg_release: 0,
          sample: "PP-B-1",
        },
        {
          region_label: 2,
          lokey: 25,
          hikey: 27,
          pitch_keycenter: 27,
          ampeg_release: 0,
          sample: "PP-D#0",
        },
        {
          region_label: 3,
          lokey: 28,
          hikey: 30,
          pitch_keycenter: 29,
          ampeg_release: 0,
          sample: "PP-F0",
        },
        {
          region_label: 4,
          lokey: 31,
          hikey: 32,
          pitch_keycenter: 31,
          ampeg_release: 0,
          sample: "PP-G0",
        },
        {
          region_label: 5,
          lokey: 33,
          hikey: 34,
          pitch_keycenter: 33,
          ampeg_release: 0,
          sample: "PP-A0",
        },
        {
          region_label: 6,
          lokey: 35,
          hikey: 35,
          pitch_keycenter: 35,
          ampeg_release: 0,
          sample: "PP-B0",
          offset: 618,
        },
        {
          region_label: 7,
          lokey: 36,
          hikey: 37,
          pitch_keycenter: 37,
          sample: "PP-C#1",
          volume: 1,
        },
        {
          region_label: 8,
          lokey: 38,
          hikey: 39,
          pitch_keycenter: 38,
          sample: "PP-D1",
          offset: 1046,
        },
        {
          region_label: 9,
          lokey: 40,
          hikey: 40,
          pitch_keycenter: 40,
          sample: "PP-E1",
        },
        {
          region_label: 10,
          lokey: 41,
          hikey: 41,
          pitch_keycenter: 41,
          sample: "PP-F1",
        },
        {
          region_label: 11,
          lokey: 42,
          hikey: 44,
          pitch_keycenter: 43,
          sample: "PP-G1",
        },
        {
          region_label: 12,
          lokey: 45,
          hikey: 46,
          pitch_keycenter: 45,
          sample: "PP-A1",
        },
        {
          region_label: 13,
          lokey: 47,
          hikey: 47,
          pitch_keycenter: 47,
          sample: "PP-B1",
        },
        {
          region_label: 14,
          lokey: 48,
          hikey: 49,
          pitch_keycenter: 48,
          sample: "PP-C2",
        },
        {
          region_label: 15,
          lokey: 50,
          hikey: 50,
          pitch_keycenter: 50,
          sample: "PP-D2",
        },
        {
          region_label: 16,
          lokey: 51,
          hikey: 52,
          pitch_keycenter: 52,
          sample: "PP-E2",
        },
        {
          region_label: 17,
          lokey: 53,
          hikey: 54,
          pitch_keycenter: 53,
          sample: "PP-F2",
        },
        {
          region_label: 18,
          lokey: 55,
          hikey: 55,
          pitch_keycenter: 55,
          sample: "PP-G2",
        },
        {
          region_label: 19,
          lokey: 56,
          hikey: 56,
          pitch_keycenter: 56,
          sample: "PP-G#2",
        },
        {
          region_label: 20,
          lokey: 57,
          hikey: 57,
          pitch_keycenter: 57,
          sample: "PP-A2",
        },
        {
          region_label: 21,
          lokey: 58,
          hikey: 58,
          pitch_keycenter: 58,
          sample: "PP-A#2",
        },
        {
          region_label: 22,
          lokey: 59,
          hikey: 59,
          pitch_keycenter: 59,
          sample: "PP-B2",
        },
        {
          region_label: 23,
          lokey: 60,
          hikey: 61,
          pitch_keycenter: 60,
          sample: "PP-C3",
        },
        {
          region_label: 24,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 62,
          sample: "PP-D3",
        },
        {
          region_label: 25,
          lokey: 64,
          hikey: 64,
          pitch_keycenter: 64,
          sample: "PP-E3",
        },
        {
          region_label: 26,
          lokey: 65,
          hikey: 66,
          pitch_keycenter: 65,
          sample: "PP-F3",
        },
        {
          region_label: 27,
          lokey: 67,
          hikey: 68,
          pitch_keycenter: 67,
          sample: "PP-G3",
        },
        {
          region_label: 28,
          lokey: 69,
          hikey: 69,
          pitch_keycenter: 69,
          sample: "PP-A3",
        },
        {
          region_label: 29,
          lokey: 70,
          hikey: 71,
          pitch_keycenter: 71,
          sample: "PP-B3",
        },
        {
          region_label: 30,
          lokey: 72,
          hikey: 73,
          pitch_keycenter: 72,
          sample: "PP-C4",
        },
        {
          region_label: 31,
          lokey: 74,
          hikey: 75,
          pitch_keycenter: 74,
          sample: "PP-D4",
        },
        {
          region_label: 32,
          lokey: 76,
          hikey: 76,
          pitch_keycenter: 76,
          sample: "PP-E4",
        },
        {
          region_label: 33,
          lokey: 77,
          hikey: 78,
          pitch_keycenter: 77,
          sample: "PP-F4",
        },
        {
          region_label: 34,
          lokey: 79,
          hikey: 79,
          pitch_keycenter: 79,
          sample: "PP-G4",
        },
        {
          region_label: 35,
          lokey: 80,
          hikey: 80,
          pitch_keycenter: 80,
          sample: "PP-G#4",
        },
        {
          region_label: 36,
          lokey: 81,
          hikey: 81,
          pitch_keycenter: 81,
          sample: "PP-A4",
        },
        {
          region_label: 37,
          lokey: 82,
          hikey: 82,
          pitch_keycenter: 82,
          sample: "PP-A#4",
        },
        {
          region_label: 38,
          lokey: 83,
          hikey: 83,
          pitch_keycenter: 83,
          sample: "PP-B4",
        },
        {
          region_label: 39,
          lokey: 84,
          hikey: 85,
          pitch_keycenter: 85,
          ampeg_release: 0,
          sample: "PP-C#5",
        },
        {
          region_label: 40,
          lokey: 86,
          hikey: 86,
          pitch_keycenter: 86,
          ampeg_release: 0,
          sample: "PP-D5",
        },
        {
          region_label: 41,
          lokey: 87,
          hikey: 87,
          pitch_keycenter: 87,
          ampeg_release: 0,
          sample: "PP-D#5",
        },
        {
          region_label: 42,
          lokey: 88,
          hikey: 89,
          pitch_keycenter: 89,
          ampeg_release: 0,
          sample: "PP-F5",
        },
        {
          region_label: 43,
          lokey: 90,
          hikey: 90,
          pitch_keycenter: 90,
          ampeg_release: 0,
          sample: "PP-F#5",
          pan: -40,
        },
        {
          region_label: 44,
          lokey: 91,
          hikey: 91,
          pitch_keycenter: 91,
          ampeg_release: 10,
          sample: "PP-G5",
          pan: -30,
          offset: 135,
        },
        {
          region_label: 45,
          lokey: 92,
          hikey: 92,
          pitch_keycenter: 92,
          ampeg_release: 10,
          sample: "PP-G#5",
          pan: -30,
        },
        {
          region_label: 46,
          lokey: 93,
          hikey: 93,
          pitch_keycenter: 93,
          ampeg_release: 10,
          sample: "PP-A5",
          pan: -45,
        },
        {
          region_label: 47,
          lokey: 94,
          hikey: 94,
          pitch_keycenter: 94,
          ampeg_release: 10,
          sample: "PP-A#5",
          pan: -45,
        },
        {
          region_label: 48,
          lokey: 95,
          hikey: 95,
          pitch_keycenter: 95,
          ampeg_release: 10,
          sample: "PP-B5",
          offset: 324,
        },
        {
          region_label: 49,
          lokey: 96,
          hikey: 96,
          pitch_keycenter: 96,
          ampeg_release: 10,
          sample: "PP-C6",
          offset: 57,
        },
        {
          region_label: 50,
          lokey: 97,
          hikey: 97,
          pitch_keycenter: 97,
          ampeg_release: 10,
          sample: "PP-C#6",
          offset: 265,
        },
        {
          region_label: 51,
          lokey: 98,
          hikey: 98,
          pitch_keycenter: 98,
          ampeg_release: 10,
          sample: "PP-D6",
        },
        {
          region_label: 52,
          lokey: 99,
          hikey: 99,
          pitch_keycenter: 99,
          ampeg_release: 10,
          sample: "PP-D#6",
        },
        {
          region_label: 53,
          lokey: 100,
          hikey: 100,
          pitch_keycenter: 100,
          ampeg_release: 10,
          sample: "PP-E6",
        },
        {
          region_label: 54,
          lokey: 101,
          hikey: 101,
          pitch_keycenter: 101,
          ampeg_release: 10,
          sample: "PP-F6",
        },
        {
          region_label: 55,
          lokey: 102,
          hikey: 102,
          pitch_keycenter: 102,
          ampeg_release: 10,
          sample: "PP-F#6",
        },
        {
          region_label: 56,
          lokey: 103,
          hikey: 103,
          pitch_keycenter: 103,
          ampeg_release: 10,
          sample: "PP-G6",
        },
        {
          region_label: 57,
          lokey: 104,
          hikey: 104,
          pitch_keycenter: 104,
          ampeg_release: 10,
          sample: "PP-G#6",
        },
        {
          region_label: 58,
          lokey: 105,
          hikey: 105,
          pitch_keycenter: 105,
          ampeg_release: 10,
          sample: "PP-A6",
          offset: 146,
        },
        {
          region_label: 59,
          lokey: 106,
          hikey: 106,
          pitch_keycenter: 106,
          ampeg_release: 10,
          sample: "PP-A#6",
        },
        {
          region_label: 60,
          lokey: 107,
          hikey: 107,
          pitch_keycenter: 107,
          ampeg_release: 10,
          sample: "PP-B6",
        },
      ],
      lovel: 41,
      hivel: 67,
      group_volume: 0,
      group_label: "PP",
    },
    {
      regions: [
        {
          region_label: 61,
          lokey: 108,
          hikey: 108,
          pitch_keycenter: 108,
          ampeg_release: 10,
          sample: "PP-C7",
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 24,
          pitch_keycenter: 23,
          ampeg_release: 0,
          sample: "Mp-B-1",
        },
        {
          region_label: 2,
          lokey: 25,
          hikey: 27,
          pitch_keycenter: 27,
          ampeg_release: 0,
          sample: "Mp-D#0",
        },
        {
          region_label: 3,
          lokey: 28,
          hikey: 30,
          pitch_keycenter: 29,
          ampeg_release: 0,
          sample: "Mp-F0",
        },
        {
          region_label: 4,
          lokey: 31,
          hikey: 32,
          pitch_keycenter: 31,
          ampeg_release: 0,
          sample: "Mp-G0",
        },
        {
          region_label: 5,
          lokey: 33,
          hikey: 34,
          pitch_keycenter: 33,
          ampeg_release: 0,
          sample: "Mp-A0",
        },
        {
          region_label: 6,
          lokey: 35,
          hikey: 35,
          pitch_keycenter: 35,
          ampeg_release: 0,
          sample: "Mp-B0",
        },
        {
          region_label: 7,
          lokey: 36,
          hikey: 37,
          pitch_keycenter: 37,
          sample: "Mp-C#1",
        },
        {
          region_label: 8,
          lokey: 38,
          hikey: 39,
          pitch_keycenter: 38,
          sample: "Mp-D1",
        },
        {
          region_label: 9,
          lokey: 40,
          hikey: 40,
          pitch_keycenter: 40,
          sample: "Mp-E1",
        },
        {
          region_label: 10,
          lokey: 41,
          hikey: 41,
          pitch_keycenter: 41,
          sample: "Mp-F1",
        },
        {
          region_label: 11,
          lokey: 42,
          hikey: 44,
          pitch_keycenter: 43,
          sample: "Mp-G1",
        },
        {
          region_label: 12,
          lokey: 45,
          hikey: 46,
          pitch_keycenter: 45,
          sample: "Mp-A1",
        },
        {
          region_label: 13,
          lokey: 47,
          hikey: 47,
          pitch_keycenter: 47,
          sample: "Mp-B1",
        },
        {
          region_label: 14,
          lokey: 48,
          hikey: 49,
          pitch_keycenter: 48,
          sample: "Mp-C2",
        },
        {
          region_label: 15,
          lokey: 50,
          hikey: 50,
          pitch_keycenter: 50,
          sample: "Mp-D2",
        },
        {
          region_label: 16,
          lokey: 51,
          hikey: 52,
          pitch_keycenter: 52,
          sample: "Mp-E2",
        },
        {
          region_label: 17,
          lokey: 53,
          hikey: 54,
          pitch_keycenter: 53,
          sample: "Mp-F2",
        },
        {
          region_label: 18,
          lokey: 55,
          hikey: 55,
          pitch_keycenter: 55,
          sample: "Mp-G2",
        },
        {
          region_label: 19,
          lokey: 56,
          hikey: 56,
          pitch_keycenter: 56,
          sample: "Mp-G#2",
        },
        {
          region_label: 20,
          lokey: 57,
          hikey: 57,
          pitch_keycenter: 57,
          sample: "Mp-A2",
        },
        {
          region_label: 21,
          lokey: 58,
          hikey: 58,
          pitch_keycenter: 58,
          sample: "Mp-A#2",
        },
        {
          region_label: 22,
          lokey: 59,
          hikey: 59,
          pitch_keycenter: 59,
          sample: "Mp-B2",
        },
        {
          region_label: 23,
          lokey: 60,
          hikey: 61,
          pitch_keycenter: 60,
          sample: "Mp-C3",
        },
        {
          region_label: 24,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 62,
          sample: "Mp-D3",
          offset: 11,
        },
        {
          region_label: 25,
          lokey: 64,
          hikey: 64,
          pitch_keycenter: 64,
          sample: "Mp-E3",
        },
        {
          region_label: 26,
          lokey: 65,
          hikey: 66,
          pitch_keycenter: 65,
          sample: "Mp-F3",
        },
        {
          region_label: 27,
          lokey: 67,
          hikey: 68,
          pitch_keycenter: 67,
          sample: "Mp-G3",
        },
        {
          region_label: 28,
          lokey: 69,
          hikey: 69,
          pitch_keycenter: 69,
          sample: "Mp-A3",
        },
        {
          region_label: 29,
          lokey: 70,
          hikey: 71,
          pitch_keycenter: 71,
          sample: "Mp-B3",
        },
        {
          region_label: 30,
          lokey: 72,
          hikey: 73,
          pitch_keycenter: 72,
          sample: "Mp-C4",
        },
        {
          region_label: 31,
          lokey: 74,
          hikey: 75,
          pitch_keycenter: 74,
          sample: "Mp-D4",
        },
        {
          region_label: 32,
          lokey: 76,
          hikey: 76,
          pitch_keycenter: 76,
          sample: "Mp-E4",
        },
        {
          region_label: 33,
          lokey: 77,
          hikey: 78,
          pitch_keycenter: 77,
          sample: "Mp-F4",
        },
        {
          region_label: 34,
          lokey: 79,
          hikey: 79,
          pitch_keycenter: 79,
          sample: "Mp-G4",
        },
        {
          region_label: 35,
          lokey: 80,
          hikey: 80,
          pitch_keycenter: 80,
          sample: "Mp-G#4",
        },
        {
          region_label: 36,
          lokey: 81,
          hikey: 81,
          pitch_keycenter: 81,
          sample: "Mp-A4",
        },
        {
          region_label: 37,
          lokey: 82,
          hikey: 82,
          pitch_keycenter: 82,
          sample: "Mp-A#4",
        },
        {
          region_label: 38,
          lokey: 83,
          hikey: 83,
          pitch_keycenter: 83,
          sample: "Mp-B4",
        },
        {
          region_label: 39,
          lokey: 84,
          hikey: 85,
          pitch_keycenter: 85,
          ampeg_release: 0,
          sample: "Mp-C#5",
        },
        {
          region_label: 40,
          lokey: 86,
          hikey: 86,
          pitch_keycenter: 86,
          ampeg_release: 0,
          sample: "Mp-D5",
        },
        {
          region_label: 41,
          lokey: 87,
          hikey: 87,
          pitch_keycenter: 87,
          ampeg_release: 0,
          sample: "Mp-D#5",
        },
        {
          region_label: 42,
          lokey: 88,
          hikey: 88,
          pitch_keycenter: 88,
          ampeg_release: 0,
          sample: "Mp-E5",
        },
        {
          region_label: 43,
          lokey: 89,
          hikey: 89,
          pitch_keycenter: 89,
          ampeg_release: 0,
          sample: "Mp-F5",
        },
        {
          region_label: 44,
          lokey: 90,
          hikey: 90,
          pitch_keycenter: 90,
          ampeg_release: 0,
          sample: "Mp-F#5",
        },
        {
          region_label: 45,
          lokey: 91,
          hikey: 91,
          pitch_keycenter: 91,
          ampeg_release: 10,
          sample: "Mp-G5",
        },
        {
          region_label: 46,
          lokey: 92,
          hikey: 92,
          pitch_keycenter: 92,
          ampeg_release: 10,
          sample: "Mp-G#5",
        },
        {
          region_label: 47,
          lokey: 93,
          hikey: 93,
          pitch_keycenter: 93,
          ampeg_release: 10,
          sample: "Mp-A5",
        },
        {
          region_label: 48,
          lokey: 94,
          hikey: 94,
          pitch_keycenter: 94,
          ampeg_release: 10,
          sample: "Mp-A#5",
        },
        {
          region_label: 49,
          lokey: 95,
          hikey: 95,
          pitch_keycenter: 95,
          ampeg_release: 10,
          sample: "Mp-B5",
        },
        {
          region_label: 50,
          lokey: 96,
          hikey: 96,
          pitch_keycenter: 96,
          ampeg_release: 10,
          sample: "Mp-C6",
        },
        {
          region_label: 51,
          lokey: 97,
          hikey: 97,
          pitch_keycenter: 97,
          ampeg_release: 10,
          sample: "Mp-C#6",
        },
        {
          region_label: 52,
          lokey: 98,
          hikey: 98,
          pitch_keycenter: 98,
          ampeg_release: 10,
          sample: "Mp-D6",
        },
        {
          region_label: 53,
          lokey: 99,
          hikey: 99,
          pitch_keycenter: 99,
          ampeg_release: 10,
          sample: "Mp-D#6",
        },
        {
          region_label: 54,
          lokey: 100,
          hikey: 100,
          pitch_keycenter: 100,
          ampeg_release: 10,
          sample: "PP-E6",
        },
        {
          region_label: 55,
          lokey: 101,
          hikey: 101,
          pitch_keycenter: 101,
          ampeg_release: 10,
          sample: "Mp-F6",
        },
        {
          region_label: 56,
          lokey: 102,
          hikey: 102,
          pitch_keycenter: 102,
          ampeg_release: 10,
          sample: "Mp-F#6",
        },
        {
          region_label: 57,
          lokey: 103,
          hikey: 103,
          pitch_keycenter: 103,
          ampeg_release: 10,
          sample: "Mp-G6",
        },
        {
          region_label: 58,
          lokey: 104,
          hikey: 104,
          pitch_keycenter: 104,
          ampeg_release: 10,
          sample: "Mp-G#6",
        },
        {
          region_label: 59,
          lokey: 105,
          hikey: 105,
          pitch_keycenter: 105,
          ampeg_release: 10,
          sample: "Mp-A6",
        },
        {
          region_label: 60,
          lokey: 106,
          hikey: 106,
          pitch_keycenter: 106,
          ampeg_release: 10,
          sample: "Mp-A#6",
        },
        {
          region_label: 61,
          lokey: 107,
          hikey: 107,
          pitch_keycenter: 107,
          ampeg_release: 10,
          sample: "PP-B6",
        },
      ],
      lovel: 68,
      hivel: 84,
      group_volume: 0,
      group_label: "MP",
    },
    {
      regions: [
        {
          region_label: 62,
          lokey: 108,
          hikey: 108,
          pitch_keycenter: 108,
          ampeg_release: 10,
          sample: "PP-C7",
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 24,
          pitch_keycenter: 23,
          ampeg_release: 0,
          sample: "Mf-B-1",
        },
        {
          region_label: 2,
          lokey: 25,
          hikey: 27,
          pitch_keycenter: 27,
          ampeg_release: 0,
          sample: "Mf-D#0",
        },
        {
          region_label: 3,
          lokey: 28,
          hikey: 30,
          pitch_keycenter: 29,
          ampeg_release: 0,
          sample: "Mf-F0",
        },
        {
          region_label: 4,
          lokey: 31,
          hikey: 32,
          pitch_keycenter: 31,
          ampeg_release: 0,
          sample: "Mf-G0",
        },
        {
          region_label: 5,
          lokey: 33,
          hikey: 34,
          pitch_keycenter: 33,
          ampeg_release: 0,
          sample: "Mf-A0",
        },
        {
          region_label: 6,
          lokey: 35,
          hikey: 35,
          pitch_keycenter: 35,
          ampeg_release: 0,
          sample: "Mf-B0",
        },
        {
          region_label: 7,
          lokey: 36,
          hikey: 37,
          pitch_keycenter: 37,
          sample: "MF-C#1",
        },
        {
          region_label: 8,
          lokey: 38,
          hikey: 39,
          pitch_keycenter: 38,
          sample: "MF-D1",
        },
        {
          region_label: 9,
          lokey: 40,
          hikey: 40,
          pitch_keycenter: 40,
          sample: "MF-E1",
        },
        {
          region_label: 10,
          lokey: 41,
          hikey: 41,
          pitch_keycenter: 41,
          sample: "MF-F1",
        },
        {
          region_label: 11,
          lokey: 42,
          hikey: 44,
          pitch_keycenter: 43,
          sample: "MF-G1",
        },
        {
          region_label: 12,
          lokey: 45,
          hikey: 46,
          pitch_keycenter: 45,
          sample: "MF-A1",
        },
        {
          region_label: 13,
          lokey: 47,
          hikey: 47,
          pitch_keycenter: 47,
          sample: "MF-B1",
        },
        {
          region_label: 14,
          lokey: 48,
          hikey: 49,
          pitch_keycenter: 48,
          sample: "MF-C2",
        },
        {
          region_label: 15,
          lokey: 50,
          hikey: 50,
          pitch_keycenter: 50,
          sample: "MF-D2",
        },
        {
          region_label: 16,
          lokey: 51,
          hikey: 52,
          pitch_keycenter: 52,
          sample: "MF-E2",
        },
        {
          region_label: 17,
          lokey: 53,
          hikey: 54,
          pitch_keycenter: 53,
          sample: "MF-F2",
        },
        {
          region_label: 18,
          lokey: 55,
          hikey: 55,
          pitch_keycenter: 55,
          sample: "MF-G2",
        },
        {
          region_label: 19,
          lokey: 56,
          hikey: 56,
          pitch_keycenter: 56,
          sample: "MF-G#2",
        },
        {
          region_label: 20,
          lokey: 57,
          hikey: 57,
          pitch_keycenter: 57,
          sample: "MF-A2",
        },
        {
          region_label: 21,
          lokey: 58,
          hikey: 58,
          pitch_keycenter: 58,
          sample: "MF-A#2",
        },
        {
          region_label: 22,
          lokey: 59,
          hikey: 59,
          pitch_keycenter: 59,
          sample: "MF-B2",
        },
        {
          region_label: 23,
          lokey: 60,
          hikey: 61,
          pitch_keycenter: 60,
          sample: "MF-C3",
        },
        {
          region_label: 24,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 62,
          sample: "MF-D3",
        },
        {
          region_label: 25,
          lokey: 64,
          hikey: 64,
          pitch_keycenter: 64,
          sample: "MF-E3",
        },
        {
          region_label: 26,
          lokey: 65,
          hikey: 66,
          pitch_keycenter: 65,
          sample: "MF-F3",
        },
        {
          region_label: 27,
          lokey: 67,
          hikey: 68,
          pitch_keycenter: 67,
          sample: "MF-G3",
        },
        {
          region_label: 28,
          lokey: 69,
          hikey: 69,
          pitch_keycenter: 69,
          sample: "MF-A3",
        },
        {
          region_label: 29,
          lokey: 70,
          hikey: 71,
          pitch_keycenter: 71,
          sample: "MF-B3",
        },
        {
          region_label: 30,
          lokey: 72,
          hikey: 73,
          pitch_keycenter: 72,
          sample: "MF-C4",
        },
        {
          region_label: 31,
          lokey: 74,
          hikey: 75,
          pitch_keycenter: 74,
          sample: "Mf-D4",
        },
        {
          region_label: 32,
          lokey: 76,
          hikey: 76,
          pitch_keycenter: 76,
          sample: "Mf-E4",
        },
        {
          region_label: 33,
          lokey: 77,
          hikey: 78,
          pitch_keycenter: 77,
          sample: "Mf-F4",
        },
        {
          region_label: 34,
          lokey: 79,
          hikey: 79,
          pitch_keycenter: 79,
          sample: "Mf-G4",
        },
        {
          region_label: 35,
          lokey: 80,
          hikey: 80,
          pitch_keycenter: 80,
          sample: "Mf-G#4",
        },
        {
          region_label: 36,
          lokey: 81,
          hikey: 81,
          pitch_keycenter: 81,
          sample: "Mf-A4",
        },
        {
          region_label: 37,
          lokey: 82,
          hikey: 82,
          pitch_keycenter: 82,
          sample: "Mf-A#4",
        },
        {
          region_label: 38,
          lokey: 83,
          hikey: 83,
          pitch_keycenter: 83,
          sample: "Mf-B4",
        },
        {
          region_label: 39,
          lokey: 84,
          hikey: 85,
          pitch_keycenter: 85,
          ampeg_release: 0,
          sample: "Mf-C#5",
        },
        {
          region_label: 40,
          lokey: 86,
          hikey: 86,
          pitch_keycenter: 86,
          ampeg_release: 0,
          sample: "Mf-D5",
        },
        {
          region_label: 41,
          lokey: 87,
          hikey: 87,
          pitch_keycenter: 87,
          ampeg_release: 0,
          sample: "Mf-D#5",
        },
        {
          region_label: 42,
          lokey: 88,
          hikey: 88,
          pitch_keycenter: 88,
          ampeg_release: 0,
          sample: "Mf-E5",
        },
        {
          region_label: 43,
          lokey: 89,
          hikey: 89,
          pitch_keycenter: 89,
          ampeg_release: 0,
          sample: "Mf-F5",
        },
        {
          region_label: 44,
          lokey: 90,
          hikey: 90,
          pitch_keycenter: 90,
          ampeg_release: 0,
          sample: "Mf-F#5",
        },
        {
          region_label: 45,
          lokey: 91,
          hikey: 91,
          pitch_keycenter: 91,
          ampeg_release: 10,
          sample: "Mf-G5",
        },
        {
          region_label: 46,
          lokey: 92,
          hikey: 92,
          pitch_keycenter: 92,
          ampeg_release: 10,
          sample: "Mf-G#5",
        },
        {
          region_label: 47,
          lokey: 93,
          hikey: 93,
          pitch_keycenter: 93,
          ampeg_release: 10,
          sample: "Mf-A5",
        },
        {
          region_label: 48,
          lokey: 94,
          hikey: 94,
          pitch_keycenter: 94,
          ampeg_release: 10,
          sample: "Mf-A#5",
        },
        {
          region_label: 49,
          lokey: 95,
          hikey: 95,
          pitch_keycenter: 95,
          ampeg_release: 10,
          sample: "Mf-B5",
        },
        {
          region_label: 50,
          lokey: 96,
          hikey: 96,
          pitch_keycenter: 96,
          ampeg_release: 10,
          sample: "Mf-C6",
        },
        {
          region_label: 51,
          lokey: 97,
          hikey: 97,
          pitch_keycenter: 97,
          ampeg_release: 10,
          sample: "Mf-C#6",
        },
        {
          region_label: 52,
          lokey: 98,
          hikey: 98,
          pitch_keycenter: 98,
          ampeg_release: 10,
          sample: "Mf-D6",
        },
        {
          region_label: 53,
          lokey: 99,
          hikey: 99,
          pitch_keycenter: 99,
          ampeg_release: 10,
          sample: "Mf-D#6",
        },
        {
          region_label: 54,
          lokey: 100,
          hikey: 100,
          pitch_keycenter: 100,
          ampeg_release: 10,
          sample: "Mf-E6",
        },
        {
          region_label: 55,
          lokey: 101,
          hikey: 101,
          pitch_keycenter: 101,
          ampeg_release: 10,
          sample: "Mf-F6",
        },
        {
          region_label: 56,
          lokey: 102,
          hikey: 102,
          pitch_keycenter: 102,
          ampeg_release: 10,
          sample: "Mf-F#6",
        },
        {
          region_label: 57,
          lokey: 103,
          hikey: 103,
          pitch_keycenter: 103,
          ampeg_release: 10,
          sample: "Mf-G6",
        },
        {
          region_label: 58,
          lokey: 104,
          hikey: 104,
          pitch_keycenter: 104,
          ampeg_release: 10,
          sample: "Mf-G#6",
        },
        {
          region_label: 59,
          lokey: 105,
          hikey: 105,
          pitch_keycenter: 105,
          ampeg_release: 10,
          sample: "Mf-A6",
        },
        {
          region_label: 60,
          lokey: 106,
          hikey: 106,
          pitch_keycenter: 106,
          ampeg_release: 10,
          sample: "Mf-A#6",
        },
        {
          region_label: 61,
          lokey: 107,
          hikey: 107,
          pitch_keycenter: 107,
          ampeg_release: 10,
          sample: "Mf-B6",
        },
      ],
      lovel: 85,
      hivel: 100,
      group_volume: 0,
      group_label: "MF",
    },
    {
      regions: [
        {
          region_label: 62,
          lokey: 108,
          hikey: 108,
          pitch_keycenter: 108,
          ampeg_release: 10,
          sample: "Mf-C7",
        },
        {
          region_label: 1,
          lokey: 21,
          hikey: 24,
          pitch_keycenter: 23,
          ampeg_release: 0,
          sample: "FF-B-1",
        },
        {
          region_label: 2,
          lokey: 25,
          hikey: 27,
          pitch_keycenter: 27,
          ampeg_release: 0,
          sample: "FF-D#0",
        },
        {
          region_label: 3,
          lokey: 28,
          hikey: 30,
          pitch_keycenter: 29,
          ampeg_release: 0,
          sample: "FF-F0",
        },
        {
          region_label: 4,
          lokey: 31,
          hikey: 32,
          pitch_keycenter: 31,
          ampeg_release: 0,
          sample: "FF-G0",
        },
        {
          region_label: 5,
          lokey: 33,
          hikey: 34,
          pitch_keycenter: 33,
          ampeg_release: 0,
          sample: "FF-A0",
        },
        {
          region_label: 6,
          lokey: 35,
          hikey: 35,
          pitch_keycenter: 35,
          ampeg_release: 0,
          sample: "FF-B0",
        },
        {
          region_label: 7,
          lokey: 36,
          hikey: 37,
          pitch_keycenter: 37,
          sample: "FF-C#1",
        },
        {
          region_label: 8,
          lokey: 38,
          hikey: 39,
          pitch_keycenter: 38,
          sample: "FF-D1",
        },
        {
          region_label: 9,
          lokey: 40,
          hikey: 40,
          pitch_keycenter: 40,
          sample: "FF-E1",
        },
        {
          region_label: 10,
          lokey: 41,
          hikey: 41,
          pitch_keycenter: 41,
          sample: "FF-F1",
        },
        {
          region_label: 11,
          lokey: 42,
          hikey: 44,
          pitch_keycenter: 43,
          sample: "FF-G1",
          offset: 100,
        },
        {
          region_label: 12,
          lokey: 45,
          hikey: 46,
          pitch_keycenter: 45,
          sample: "FF-A1",
        },
        {
          region_label: 13,
          lokey: 47,
          hikey: 47,
          pitch_keycenter: 47,
          sample: "FF-B1",
        },
        {
          region_label: 14,
          lokey: 48,
          hikey: 49,
          pitch_keycenter: 48,
          sample: "FF-C2",
        },
        {
          region_label: 15,
          lokey: 50,
          hikey: 50,
          pitch_keycenter: 50,
          sample: "FF-D2",
        },
        {
          region_label: 16,
          lokey: 51,
          hikey: 52,
          pitch_keycenter: 52,
          sample: "FF-E2",
        },
        {
          region_label: 17,
          lokey: 53,
          hikey: 54,
          pitch_keycenter: 53,
          sample: "FF-F2",
        },
        {
          region_label: 18,
          lokey: 55,
          hikey: 55,
          pitch_keycenter: 55,
          sample: "FF-G2",
        },
        {
          region_label: 19,
          lokey: 56,
          hikey: 56,
          pitch_keycenter: 56,
          sample: "FF-G#2",
        },
        {
          region_label: 20,
          lokey: 57,
          hikey: 57,
          pitch_keycenter: 57,
          sample: "FF-A2",
        },
        {
          region_label: 21,
          lokey: 58,
          hikey: 58,
          pitch_keycenter: 58,
          sample: "FF-A#2",
        },
        {
          region_label: 22,
          lokey: 59,
          hikey: 59,
          pitch_keycenter: 59,
          sample: "FF-B2",
        },
        {
          region_label: 23,
          lokey: 60,
          hikey: 61,
          pitch_keycenter: 60,
          sample: "FF-C3",
          offset: 325,
        },
        {
          region_label: 24,
          lokey: 62,
          hikey: 63,
          pitch_keycenter: 62,
          sample: "FF-D3",
        },
        {
          region_label: 25,
          lokey: 64,
          hikey: 64,
          pitch_keycenter: 64,
          sample: "FF-E3",
        },
        {
          region_label: 26,
          lokey: 65,
          hikey: 66,
          pitch_keycenter: 65,
          sample: "FF-F3",
        },
        {
          region_label: 27,
          lokey: 67,
          hikey: 68,
          pitch_keycenter: 67,
          sample: "FF-G3",
        },
        {
          region_label: 28,
          lokey: 69,
          hikey: 69,
          pitch_keycenter: 69,
          sample: "FF-A3",
        },
        {
          region_label: 29,
          lokey: 70,
          hikey: 71,
          pitch_keycenter: 71,
          sample: "FF-B3",
        },
        {
          region_label: 30,
          lokey: 72,
          hikey: 73,
          pitch_keycenter: 72,
          sample: "FF-C4",
        },
        {
          region_label: 31,
          lokey: 74,
          hikey: 75,
          pitch_keycenter: 74,
          sample: "FF-D4",
        },
        {
          region_label: 32,
          lokey: 76,
          hikey: 76,
          pitch_keycenter: 76,
          sample: "FF-E4",
        },
        {
          region_label: 33,
          lokey: 77,
          hikey: 78,
          pitch_keycenter: 77,
          sample: "FF-F4",
        },
        {
          region_label: 34,
          lokey: 79,
          hikey: 79,
          pitch_keycenter: 79,
          sample: "FF-G4",
        },
        {
          region_label: 35,
          lokey: 80,
          hikey: 80,
          pitch_keycenter: 80,
          sample: "FF-G#4",
        },
        {
          region_label: 36,
          lokey: 81,
          hikey: 81,
          pitch_keycenter: 81,
          sample: "FF-A4",
        },
        {
          region_label: 37,
          lokey: 82,
          hikey: 82,
          pitch_keycenter: 82,
          sample: "FF-A#4",
        },
        {
          region_label: 38,
          lokey: 83,
          hikey: 83,
          pitch_keycenter: 83,
          sample: "FF-B4",
        },
        {
          region_label: 39,
          lokey: 84,
          hikey: 85,
          pitch_keycenter: 85,
          ampeg_release: 0,
          sample: "FF-C#5",
        },
        {
          region_label: 40,
          lokey: 86,
          hikey: 87,
          pitch_keycenter: 86,
          ampeg_release: 0,
          sample: "FF-D5",
        },
        {
          region_label: 41,
          lokey: 88,
          hikey: 88,
          pitch_keycenter: 88,
          ampeg_release: 0,
          sample: "FF-E5",
        },
        {
          region_label: 42,
          lokey: 89,
          hikey: 90,
          pitch_keycenter: 89,
          ampeg_release: 0,
          sample: "FF-F5",
        },
        {
          region_label: 43,
          lokey: 91,
          hikey: 92,
          pitch_keycenter: 91,
          ampeg_release: 10,
          sample: "FF-G5",
        },
        {
          region_label: 44,
          lokey: 93,
          hikey: 94,
          pitch_keycenter: 93,
          ampeg_release: 10,
          sample: "FF-A5",
        },
        {
          region_label: 45,
          lokey: 95,
          hikey: 95,
          pitch_keycenter: 95,
          ampeg_release: 10,
          sample: "Mf-B5",
        },
        {
          region_label: 46,
          lokey: 96,
          hikey: 97,
          pitch_keycenter: 96,
          ampeg_release: 10,
          sample: "Mf-C6",
        },
        {
          region_label: 47,
          lokey: 98,
          hikey: 98,
          pitch_keycenter: 97,
          ampeg_release: 10,
          sample: "Mf-C#6",
        },
        {
          region_label: 48,
          lokey: 99,
          hikey: 99,
          pitch_keycenter: 98,
          ampeg_release: 10,
          sample: "Mf-D6",
        },
        {
          region_label: 49,
          lokey: 100,
          hikey: 100,
          pitch_keycenter: 99,
          ampeg_release: 10,
          sample: "Mf-D#6",
        },
        {
          region_label: 50,
          lokey: 101,
          hikey: 101,
          pitch_keycenter: 100,
          ampeg_release: 10,
          sample: "Mf-E6",
        },
        {
          region_label: 51,
          lokey: 102,
          hikey: 102,
          pitch_keycenter: 102,
          ampeg_release: 10,
          sample: "Mf-F#6",
        },
        {
          region_label: 52,
          lokey: 103,
          hikey: 103,
          pitch_keycenter: 103,
          ampeg_release: 10,
          sample: "Mf-G6",
        },
        {
          region_label: 53,
          lokey: 104,
          hikey: 104,
          pitch_keycenter: 104,
          ampeg_release: 10,
          sample: "Mf-G#6",
        },
        {
          region_label: 54,
          lokey: 105,
          hikey: 105,
          pitch_keycenter: 105,
          ampeg_release: 10,
          sample: "Mf-A6",
        },
        {
          region_label: 55,
          lokey: 106,
          hikey: 106,
          pitch_keycenter: 106,
          ampeg_release: 10,
          sample: "Mf-A#6",
        },
        {
          region_label: 56,
          lokey: 107,
          hikey: 107,
          pitch_keycenter: 107,
          ampeg_release: 10,
          sample: "Mf-B6",
        },
      ],
      lovel: 101,
      hivel: 127,
      group_volume: 0,
      group_label: "FF",
    },
  ],
};
